version: '3.8'

services:
  postgres_db:
    image: postgres:16
    container_name: PostgresContainer
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres_db:/var/lib/postgresql/data 

volumes:
  postgres_db:
    driver: local