"""update category_id column

Revision ID: c871edcae5e1
Revises: 3613c32f2b60
Create Date: 2024-02-29 00:28:52.208479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c871edcae5e1'
down_revision: Union[str, None] = '3613c32f2b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
